# Generated by Django 3.2.8 on 2021-12-26 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpaca_id', models.CharField(help_text='Enter your Alpaca id', max_length=100)),
                ('alpaca_key', models.CharField(help_text='Enter your Alpaca key', max_length=100)),
                ('user', models.ForeignKey(help_text='Associated user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
