# Generated by Django 3.2.8 on 2021-12-30 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Portfolio name', max_length=100)),
                ('user', models.ForeignKey(help_text='Associated user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='StockInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='quantity', max_digits=8)),
                ('portfolio', models.ForeignKey(help_text='Associated portfolio', on_delete=django.db.models.deletion.CASCADE, to='auth0login.portfolio')),
            ],
            options={
                'ordering': ['portfolio'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='order timestamp')),
                ('order_type', models.CharField(choices=[('MB', 'Market buy'), ('MS', 'Market sell'), ('LB', 'Limit buy'), ('LS', 'Limit sell'), ('SB', 'Stop buy'), ('SS', 'Stop sell')], help_text='order type', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, help_text='order price', max_digits=8)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='quantity', max_digits=8)),
                ('user', models.ForeignKey(help_text='Associated user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'timestamp', 'order_type'],
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpaca_id', models.CharField(help_text='Enter your Alpaca id', max_length=100)),
                ('alpaca_key', models.CharField(help_text='Enter your Alpaca key', max_length=100)),
                ('user', models.OneToOneField(help_text='Associated user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='BotInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bot Name', max_length=100)),
                ('portfolio', models.OneToOneField(blank=True, help_text='Associated portfolio', on_delete=django.db.models.deletion.CASCADE, to='auth0login.portfolio')),
                ('user', models.ForeignKey(help_text='Associated user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
