# Generated by Django 3.2.8 on 2022-01-07 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradingbot', '0004_order_portfolio_stockinstance'),
        ('auth0login', '0002_alter_portfolio_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stockinstance',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='stockinstance',
            name='stock',
        ),
        migrations.AlterField(
            model_name='botinstance',
            name='portfolio',
            field=models.OneToOneField(blank=True, help_text='Associated portfolio', on_delete=django.db.models.deletion.CASCADE, to='tradingbot.portfolio'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='StockInstance',
        ),
    ]
