# Generated by Django 3.2.8 on 2022-01-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingbot', '0002_auto_20220107_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ticker',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
