# Generated by Django 3.2.8 on 2022-01-07 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tradingbot', '0003_alter_company_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Portfolio name', max_length=100)),
                ('cash', models.DecimalField(decimal_places=2, help_text='Cash', max_digits=10)),
                ('user', models.OneToOneField(help_text='Associated user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='StockInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='quantity', max_digits=8)),
                ('portfolio', models.ForeignKey(help_text='Associated portfolio', on_delete=django.db.models.deletion.CASCADE, to='tradingbot.portfolio')),
                ('stock', models.ForeignKey(help_text='Associated stock', on_delete=django.db.models.deletion.CASCADE, to='tradingbot.stock')),
            ],
            options={
                'ordering': ['portfolio'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='order timestamp')),
                ('order_type', models.CharField(choices=[('MB', 'Market buy'), ('MS', 'Market sell'), ('LB', 'Limit buy'), ('LS', 'Limit sell'), ('SB', 'Stop buy'), ('SS', 'Stop sell')], help_text='order type', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, help_text='order price', max_digits=8)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='quantity', max_digits=8)),
                ('company', models.ForeignKey(help_text='Company', on_delete=django.db.models.deletion.CASCADE, to='tradingbot.company')),
                ('user', models.ForeignKey(help_text='Associated user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'timestamp', 'order_type', 'company'],
            },
        ),
    ]
