# Generated by Django 3.2.8 on 2022-02-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingbot', '0007_alter_portfolio_optimization_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='optimization_strategy',
            field=models.CharField(choices=[('none', 'None'), ('ma_sharp_ratio', 'Sharpe ratio based on moving average')], default='none', help_text='Optimization Strategy', max_length=50),
        ),
    ]
