# Generated by Django 3.2.8 on 2022-03-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingbot', '0008_alter_portfolio_optimization_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('F', 'Filled'), ('N', 'New'), ('C', 'Closed')], help_text='order status', max_length=1),
        ),
    ]
